namespace Common.Communication
{
    public enum Operation
    {
        PrijaviSeKorisnik,
        PrijaviSeAdmin,
        RegistrujSe,
        OdjaviSeKorisnik,
        OdjaviSeAdmin,
        VratiSveProgrameTreninga,
        PretraziProgramTreninga,
        VratiProgramTreninga,
        VratiTreninge,
        VratiPrijavuZaProgramTreninga,
        PosaljiPrijavuZaProgramTreninga,
        VratiPrijaveZaKorisnika,
        IzmeniProgramTreninga,
        ObrisiProgramTreninga,
        VratiSveGrupe,
        PretraziGrupe,
        VratiGrupu,
        IzmeniGrupu,
        ObrisiGrupu,
        VratiPrijaveZaGrupu,
        VratiPrijaveVanGrupe,
        VratiPrijaveZaProgramTreninga,
        KreirajGrupu,
        KreirajProgramTreninga
    }
}
